/* File generated by kazoo for TASTE - do not edit */
#include <limits.h>
#include <rtems.h>

#define RUNTIME_THREAD_COUNT (1 + 2)
#define RUNTIME_CYCLIC_INTERFACE_COUNT (0 + 1 + 1)
#define MAX_THREAD_NAME_SIZE 64
#define NANOSECONDS_IN_MILISECOND 1000000ULL

enum interfaces_enum {

	ponger_ping,

	ponger_trigger,

};

typedef struct {
	rtems_id id;
	char name[MAX_THREAD_NAME_SIZE];
	uint64_t thread_execution_time;
	uint64_t min_thread_execution_time;
	uint64_t max_thread_execution_time;
	double mean_thread_execution_time;
	uint64_t execution_time_counter;
} thread_info;

extern thread_info threads_info[RUNTIME_THREAD_COUNT];
